32

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,38 +68,79 @@
 #
 # Check https://circleci.com/docs/2.0/language-javascript/ for more details
 #
+# version: 2
+# jobs:
+#   build:
+#     docker:  
+#       # specify the version you desire here
+#       - image: circleci/node:8.9.0
+
+#       - image: circleci/mysql:5.7
+#         environment:
+#           MYSQL_ROOT_PASSWORD: root
+#           MYSQL_DATABASE: test
+#           MYSQL_USER: root
+#           MYSQL_PASSWORD: root
+
+#     steps:
+#       # Checkout from GIT
+#       - checkout
+
+#       - run:
+#           name: Waiting for MySQL to be ready
+#           command: |
+#             for i in `seq 1 30`;
+#             do
+#               nc -z 127.0.0.1 3306 && echo Success && exit 0
+#               echo -n .
+#               sleep 1
+#             done
+#             echo Failed waiting for MySQL && exit 1
+#       # Import DB Dump
+#       - run:
+#           name: Install MySQL CLI
+#           command: |
+#             sudo apt-get install mysql-client
+#             mysql -h 127.0.0.1 -u user -ppassw0rd test < sql-data/dummy.sql
+#             mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test.user"
+
+    
+# Javascript Node CircleCI 2.0 configuration file
+#
+# Check https://circleci.com/docs/2.0/language-javascript/ for more details
+#
 version: 2
 jobs:
   build:
-    docker:  
+    docker:
       # specify the version you desire here
       - image: circleci/node:8.9.0
+      
+      # Specify service dependencies here if necessary
+      # CircleCI maintains a library of pre-built images
+      # documented at https://circleci.com/docs/2.0/circleci-images/
+      # - image: circleci/mongo:3.4.4
 
-      - image: circleci/mysql:5.7
-        environment:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: test
-          MYSQL_USER: root
-          MYSQL_PASSWORD: root
+    working_directory: ~/repo
 
     steps:
-      # Checkout from GIT
       - checkout
 
-      - run:
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 30`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
-      # Import DB Dump
-      - run:
-          name: Install MySQL CLI
-          command: |
-            sudo apt-get install mysql-client
-            mysql -h 127.0.0.1 -u user -ppassw0rd test < sql-data/dummy.sql
-            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM test.user"
+      # Download and cache dependencies
+      - restore_cache:
+          keys:
+          - v1-dependencies-{{ checksum "package.json" }}
+          # fallback to using the latest cache if no exact match is found
+          - v1-dependencies-
+
+      - run: yarn install
+
+      - save_cache:
+          paths:
+            - node_modules
+          key: v1-dependencies-{{ checksum "package.json" }}
+        
+      # run tests!
+      - run: yarn test
+
+
